### ISSUE TITLE
quarto add does not find the master branch

### ISSUE THREAD

**Issue by jmehringer-iis** [rchaput/acronyms#1]
Hi,

first: Thanks a lot for this repo! I'll gladly give it a try and am thankful that it's here :)

I found that

`quarto add rchaput/acronyms` as described in the readme will not install the extension, since `Quarto` looks for the main branch, see [here](https://stackoverflow.com/questions/76614176/cant-use-install-a-quarto-extension-created-by-myself-from-github)

If I write `quarto add rchaput/acronyms@master`, it works though :)

Cheers

**Comment by rchaput** [comment]
Hello,

Thank you for your interest! I'm glad you find this extension helpful.

As for this issue, it's unfortunate that Quarto does not check for `master` when `main` is not found...
I will update the Readme installation instructions to help new users.
